using System;
namespace CRM.Domain.Models.Integrations
{
    public class ExcedeCustomer
    {
        public string Id { get; set; }
        public string CusId { get; set; }
        public string Name { get; set; }
        public string NameFirst { get; set; }
        public string NameMiddle { get; set; }
        public string NameLast { get; set; }
        public string NameNick { get; set; }
        public string NameSpouse { get; set; }
        public string Addr1 { get; set; }
        public string Addr2 { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string State { get; set; }
        public string Post { get; set; }
        public string Country { get; set; }
        public string BillCusId { get; set; }
        public string BillAddr1 { get; set; }
        public string BillAddr2 { get; set; }
        public string BillCity { get; set; }
        public string BillCounty { get; set; }
        public string BillState { get; set; }
        public string BillPost { get; set; }
        public string BillCountry { get; set; }
        public string PhoneHome { get; set; }
        public string PhoneWork { get; set; }
        public string PhoneOther { get; set; }
        public string PhoneFax { get; set; }
        public string Contact { get; set; }
        public int DoNotCallPhoneHome { get; set; }
        public int DoNotCallPhoneWork { get; set; }
        public int DoNotCallPhoneOther { get; set; }
        public DateTime DateDoNotCall { get; set; }
        public string EmailHome { get; set; }
        public string EmailWork { get; set; }
        public string EmailOther { get; set; }
        public string Typ { get; set; }
        public string TrmId { get; set; }
        public string ShpId { get; set; }
        public string PtTaxId { get; set; }
        public string SvTaxId { get; set; }
        public string VhTaxId { get; set; }
        public string EmpIdSpn { get; set; }
        public DateTime DateBirth { get; set; }
        public DateTime DateBirthSpouse { get; set; }
        public string DsbTypId { get; set; }
        public string MemTypId { get; set; }
        public string RecTypId { get; set; }
        public string PtSlsTypId { get; set; }
        public string SvSlsTypId { get; set; }
        public string VhSlsTypId { get; set; }
        public string FlSlsTypId { get; set; }
        public string PriIdOride { get; set; }
        public string PriIdBase { get; set; }
        public int AllowSpecialPri { get; set; }
        public int PurReqd { get; set; }
        public string PurNbr { get; set; }
        public int CoreInvoiceReqd { get; set; }
        public int Inactive { get; set; }
        public string EmpId { get; set; }
        public DateTime DateCreate { get; set; }
        public DateTime DateUpdate { get; set; }
        public DateTime DateInvoice { get; set; }
        public double AmtInvoice { get; set; }
        public DateTime DatePayment { get; set; }
        public double AmtPayment { get; set; }
        public int DaysPaymentAvg { get; set; }
        public int CutoffByCrLimit { get; set; }
        public int CutoffByAged { get; set; }
        public int CutoffAgedPeriod { get; set; }
        public double AmtCrLimit { get; set; }
        public double AmtCrLimitInvoice { get; set; }
        public int StatementReqd { get; set; }
        public DateTime DateStatement { get; set; }
        public int AllowFinanceChg { get; set; }
        public double AmtAged0 { get; set; }
        public double AmtAged1to30 { get; set; }
        public double AmtAged31to60 { get; set; }
        public double AmtAged61to90 { get; set; }
        public double AmtAgedOver90 { get; set; }
        public double AmtBalOpen { get; set; }
        public double AmtBalAccount { get; set; }
        public int NotId { get; set; }
        public int Company { get; set; }
        public string CusMisc1 { get; set; }
        public string CusMisc2 { get; set; }
        public string CusMisc3 { get; set; }
        public string CusMisc4 { get; set; }
        public string CusMisc5 { get; set; }
        public object TS { get; set; }
    }
}