using System;
using System.Collections.Generic;

namespace CRM.Domain.Models.Integrations
{
    public class ExcedeVehicle
    {
        public string Id { get; set; }     
        public string Vin { get; set; }     
        public string Make { get; set; }
        public string Model { get; set; }
        public string ModelNbr { get; set; }   
        public string ModelYear { get; set; }
        public string Series { get; set; }
        public string BodyStyle { get; set; }
        public string Transmission { get; set; }
        public int Cylinders { get; set; }
        public int HrsEngine { get; set; }
        public string ExtColorCode { get; set; }
        public string ExtColor { get; set; }
        public string IntColorCode { get; set; }
        public string IntColor { get; set; }
        public string KeyCode1 { get; set; }
        public string KeyCode2 { get; set; }
        public string CusId { get; set; }
        public string CusName { get; set; }
        public int Odom { get; set; }
        public int OdomTyp { get; set; }
        public DateTime DateInService { get; set; }
        public int Condition { get; set; }
        public string ConditionDes { get; set; }
        public string TypId { get; set; }
        public string TypIdDes { get; set; }
        public int Status { get; set; }
        public string StatusDes { get; set; }
        public string StatusNotes { get; set; }
        public int Marketability { get; set; }
        public string MarketabilityDes { get; set; }
        public double AmtMfrPrice { get; set; }
        public double AmtMfrCost { get; set; }
        public double AmtAdjPrice { get; set; }
        public double AmtAdjCost { get; set; }
        public double AmtOurPrice { get; set; }
        public double AmtOurCost { get; set; }
        public double AmtHoldBack { get; set; }
        public double AmtRebate { get; set; }
        public string BrnId { get; set; }
        public string LocId { get; set; }
        public string LocIdDes { get; set; }
        public DateTime DateReceive { get; set; }
        public string PurEmpId { get; set; }
        public string PurVenId { get; set; }
        public DateTime DateCount { get; set; }
        public string CountEmpId { get; set; }
        public double AmtDMVFees { get; set; }
        public double AmtDMVFeesNext { get; set; }
        public DateTime DateDMVFeesExpire { get; set; }
        public string DMVState { get; set; }
        public string DMVLicense { get; set; }
        public DateTime DateDMVLicenseExpire { get; set; }
        public string DMVNotes { get; set; }
        public int GVWR { get; set; }
        public string FleetUntId { get; set; }
        public string EngineMfr { get; set; }
        public string EngineModel { get; set; }
        public string EngineSerialNbr { get; set; }
        public string TransMfr { get; set; }
        public string TransModel { get; set; }
        public string TransSerialNbr { get; set; }
        public string FrontAxleMfr { get; set; }
        public string FrontAxleModel { get; set; }
        public string FrontAxleSerialNbr { get; set; }
        public string RearFrontAxleMfr { get; set; }
        public string RearFrontAxleModel { get; set; }
        public string RearFrontAxleSerialNbr { get; set; }
        public string RearAxleMfr { get; set; }
        public string RearAxleModel { get; set; }
        public string RearAxleSerialNbr { get; set; }
        public string RearAxleRatio { get; set; }
        public string Wheelbase { get; set; }
        public string Horsepower { get; set; }
        public string SuspensionTyp { get; set; }
        public string CabConfig { get; set; }
        public string FifthWheel { get; set; }
        public string EngineBrake { get; set; }
        public string Sleeper { get; set; }
        public string FuelTank { get; set; }
        public string ACCompSerialNbr { get; set; }
        public int Reefer { get; set; }
        public int PTO { get; set; }
        public int APU { get; set; }
        public int Other { get; set; }
        public string OtherDes { get; set; }
        public int HrsReefer { get; set; }
        public int HrsStandby { get; set; }
        public int HrsPTO { get; set; }
        public int HrsAPU { get; set; }
        public int HrsOther { get; set; }
        public DateTime? DateDepStart { get; set; }
        public DateTime? DateDepEnd { get; set; }
        public double AmtSalvage { get; set; }
        public double PctNote { get; set; }
        public DateTime? DateNoteStart { get; set; }
        public DateTime? DateNoteEnd { get; set; }
        public double AmtFuelTaxRep { get; set; }
        public double AmtPropTaxFee { get; set; }
        public double PctInsMarkup { get; set; }
        public string EmpId { get; set; }
        public DateTime DateCreate { get; set; }
        public DateTime DateUpdate { get; set; }
        public int NotId { get; set; }      
        public string UntMisc1 { get; set; }
        public string UntMisc2 { get; set; }
        public string UntMisc2Des { get; set; }
        public string UntMisc3 { get; set; }
        public string UntMisc3Des { get; set; }
        public string UntMisc4 { get; set; }
        public string UntMisc4Des { get; set; }
        public string UntMisc5 { get; set; }
        public string UntMisc5Des { get; set; }
        public string UntMisc6 { get; set; }
        public string UntMisc6Des { get; set; }
        public string UntMisc7 { get; set; }
        public string UntMisc7Des { get; set; }
        public string UntMisc8 { get; set; }
        public string UntMisc8Des { get; set; }
        public string UntMisc9 { get; set; }
        public string UntMisc9Des { get; set; }
        public string UntMisc10 { get; set; }
        public string UntMisc10Des { get; set; }
        public string UntMisc11 { get; set; }
        public string UntMisc11Des { get; set; }
        public string UntMisc12 { get; set; }
        public string UntMisc13 { get; set; }
        public string UntMisc14 { get; set; }
        public string UntMisc15 { get; set; }
        public string UntMisc16 { get; set; }
        public string UntMisc17 { get; set; }
        public string UntMisc18 { get; set; }
        public string UntMisc18Des { get; set; }
        public string UntMisc19 { get; set; }
        public string UntMisc20 { get; set; }
        public string UntMisc21 { get; set; }
        public string UntMisc21Des { get; set; }
        public string UntMisc22 { get; set; }
        public string UntMisc22Des { get; set; }
        public string UntMisc23 { get; set; }
        public string UntMisc24 { get; set; }
        public string UntMisc25 { get; set; }
        public string UntMisc26 { get; set; }
        public string UntMisc27 { get; set; }
        public string UntMisc28 { get; set; }
        public string UntMisc29 { get; set; }
        public string UntMisc30 { get; set; }
        public string UntMisc30Des { get; set; }
        public string UntMisc31 { get; set; }
        public string UntMisc31Des { get; set; }
        public string UntMisc32 { get; set; }
        public string UntMisc32Des { get; set; }
        public string UntMisc33 { get; set; }
        public string UntMisc33Des { get; set; }
        public string UntMisc34 { get; set; }
        public string UntMisc34Des { get; set; }
        public string UntMisc35 { get; set; }
        public string UntMisc36 { get; set; }
        public string UntMisc37 { get; set; }
        public string UntMisc38 { get; set; }
        public string UntMisc38Des { get; set; }
        public string UntMisc39 { get; set; }
        public string UntMisc39Des { get; set; }
        public string UntMisc40 { get; set; }
        public string UntMisc40Des { get; set; }    
        public object TS { get; set; }
    }
}