namespace CRM.Domain.Models.Integrations
{
    public class ExcedeCompanyControl
    {
        public string Id { get; set; }
        public string SerialNbr { get; set; }
        public string GenerationDelimiter { get; set; }
        public int EmpIdAuto { get; set; }
        public int EmpIdLast { get; set; }
        public string EmpMiscDes1 { get; set; }
        public string EmpMiscDes2 { get; set; }
        public string EmpMiscDes3 { get; set; }
        public string EmpMiscDes4 { get; set; }
        public string EmpMiscDes5 { get; set; }
        public int CusIdAuto { get; set; }
        public int CusIdLast { get; set; }
        public string CusMiscDes1 { get; set; }
        public string CusMiscDes2 { get; set; }
        public string CusMiscDes3 { get; set; }
        public string CusMiscDes4 { get; set; }
        public string CusMiscDes5 { get; set; }
        public int VenIdAuto { get; set; }
        public int VenIdLast { get; set; }
        public string VenMiscDes1 { get; set; }
        public string VenMiscDes2 { get; set; }
        public string VenMiscDes3 { get; set; }
        public string VenMiscDes4 { get; set; }
        public string VenMiscDes5 { get; set; }
        public string PrtMiscDes1 { get; set; }
        public string PrtMiscDes2 { get; set; }
        public string PrtMiscDes3 { get; set; }
        public string PrtMiscDes4 { get; set; }
        public string PrtMiscDes5 { get; set; }
        public string McaMiscDes1 { get; set; }
        public string McaMiscDes2 { get; set; }
        public string McaMiscDes3 { get; set; }
        public string McaMiscDes4 { get; set; }
        public string McaMiscDes5 { get; set; }
        public string LbrMiscDes1 { get; set; }
        public string LbrMiscDes2 { get; set; }
        public string LbrMiscDes3 { get; set; }
        public string LbrMiscDes4 { get; set; }
        public string LbrMiscDes5 { get; set; }
        public string BrnMiscDes1 { get; set; }
        public string BrnMiscDes2 { get; set; }
        public string BrnMiscDes3 { get; set; }
        public string BrnMiscDes4 { get; set; }
        public string BrnMiscDes5 { get; set; }
        public string BrnMiscDes6 { get; set; }
        public string BrnMiscDes7 { get; set; }
        public string BrnMiscDes8 { get; set; }
        public string BrnMiscDes9 { get; set; }
        public string BrnMiscDes10 { get; set; }
        public string BrnMiscDes11 { get; set; }
        public string BrnMiscDes12 { get; set; }
        public string BrnMiscDes13 { get; set; }
        public string BrnMiscDes14 { get; set; }
        public string BrnMiscDes15 { get; set; }
        public string BrnMiscDes16 { get; set; }
        public string BrnMiscDes17 { get; set; }
        public string BrnMiscDes18 { get; set; }
        public string BrnMiscDes19 { get; set; }
        public string BrnMiscDes20 { get; set; }
        public int UntIdAuto { get; set; }
        public int UntIdLast { get; set; }
        public string UntMiscDes1 { get; set; }
        public string UntMiscDes2 { get; set; }
        public string UntMiscDes3 { get; set; }
        public string UntMiscDes4 { get; set; }
        public string UntMiscDes5 { get; set; }
        public string UntMiscDes6 { get; set; }
        public string UntMiscDes7 { get; set; }
        public string UntMiscDes8 { get; set; }
        public string UntMiscDes9 { get; set; }
        public string UntMiscDes10 { get; set; }
        public string UntMiscDes11 { get; set; }
        public string UntMiscDes12 { get; set; }
        public string UntMiscDes13 { get; set; }
        public string UntMiscDes14 { get; set; }
        public string UntMiscDes15 { get; set; }
        public string UntMiscDes16 { get; set; }
        public string UntMiscDes17 { get; set; }
        public string UntMiscDes18 { get; set; }
        public string UntMiscDes19 { get; set; }
        public string UntMiscDes20 { get; set; }
        public string UntMiscDes21 { get; set; }
        public string UntMiscDes22 { get; set; }
        public string UntMiscDes23 { get; set; }
        public string UntMiscDes24 { get; set; }
        public string UntMiscDes25 { get; set; }
        public string UntMiscDes26 { get; set; }
        public string UntMiscDes27 { get; set; }
        public string UntMiscDes28 { get; set; }
        public string UntMiscDes29 { get; set; }
        public string UntMiscDes30 { get; set; }
        public string UntMiscDes31 { get; set; }
        public string UntMiscDes32 { get; set; }
        public string UntMiscDes33 { get; set; }
        public string UntMiscDes34 { get; set; }
        public string UntMiscDes35 { get; set; }
        public string UntMiscDes36 { get; set; }
        public string UntMiscDes37 { get; set; }
        public string UntMiscDes38 { get; set; }
        public string UntMiscDes39 { get; set; }
        public string UntMiscDes40 { get; set; }
        public string SlsMiscDes1 { get; set; }
        public string SlsMiscDes2 { get; set; }
        public string SlsMiscDes3 { get; set; }
        public string SlsMiscDes4 { get; set; }
        public string SlsMiscDes5 { get; set; }
        public string SlsMiscDes6 { get; set; }
        public string SlsMiscDes7 { get; set; }
        public string SlsMiscDes8 { get; set; }
        public string SlsMiscDes9 { get; set; }
        public string SlsMiscDes10 { get; set; }
        public string SlsMiscDes11 { get; set; }
        public string SlsMiscDes12 { get; set; }
        public string SlsMiscDes13 { get; set; }
        public string SlsMiscDes14 { get; set; }
        public string SlsMiscDes15 { get; set; }
        public string SlsMiscDes16 { get; set; }
        public string SlsMiscDes17 { get; set; }
        public string SlsMiscDes18 { get; set; }
        public string SlsMiscDes19 { get; set; }
        public string SlsMiscDes20 { get; set; }
        public string SlsMiscDes21 { get; set; }
        public string SlsMiscDes22 { get; set; }
        public string SlsMiscDes23 { get; set; }
        public string SlsMiscDes24 { get; set; }
        public string SlsMiscDes25 { get; set; }
        public string SlsMiscDes26 { get; set; }
        public string SlsMiscDes27 { get; set; }
        public string SlsMiscDes28 { get; set; }
        public string SlsMiscDes29 { get; set; }
        public string SlsMiscDes30 { get; set; }
        public string SlsMiscDes31 { get; set; }
        public string SlsMiscDes32 { get; set; }
        public string SlsMiscDes33 { get; set; }
        public string SlsMiscDes34 { get; set; }
        public string SlsMiscDes35 { get; set; }
        public string SlsMiscDes36 { get; set; }
        public string SlsMiscDes37 { get; set; }
        public string SlsMiscDes38 { get; set; }
        public string SlsMiscDes39 { get; set; }
        public string SlsMiscDes40 { get; set; }
        public int CountryCode { get; set; }
        public string TaxDes1 { get; set; }
        public string TaxDes2 { get; set; }
        public string MlsMiscDes1 { get; set; }
        public string MlsMiscDes2 { get; set; }
        public string MlsMiscDes3 { get; set; }
        public string MlsMiscDes4 { get; set; }
        public string MlsMiscDes5 { get; set; }
        public string MlsMiscDes6 { get; set; }
        public string MlsMiscDes7 { get; set; }
        public string MlsMiscDes8 { get; set; }
        public string MlsMiscDes9 { get; set; }
        public string MlsMiscDes10 { get; set; }
        public string MlsMiscDes11 { get; set; }
        public string MlsMiscDes12 { get; set; }
        public string MlsMiscDes13 { get; set; }
        public string MlsMiscDes14 { get; set; }
        public string MlsMiscDes15 { get; set; }
        public string MlsMiscDes16 { get; set; }
        public string MlsMiscDes17 { get; set; }
        public string MlsMiscDes18 { get; set; }
        public string MlsMiscDes19 { get; set; }
        public string MlsMiscDes20 { get; set; }
        public string MlsVinMiscDes1 { get; set; }
        public string MlsVinMiscDes2 { get; set; }
        public string MlsVinMiscDes3 { get; set; }
        public string MlsVinMiscDes4 { get; set; }
        public string MlsVinMiscDes5 { get; set; }
        public string MlsVinMiscDes6 { get; set; }
        public string MlsVinMiscDes7 { get; set; }
        public string MlsVinMiscDes8 { get; set; }
        public string MlsVinMiscDes9 { get; set; }
        public string MlsVinMiscDes10 { get; set; }
        public string MlsVinMiscDes11 { get; set; }
        public string MlsVinMiscDes12 { get; set; }
        public string MlsVinMiscDes13 { get; set; }
        public string MlsVinMiscDes14 { get; set; }
        public string MlsVinMiscDes15 { get; set; }
        public string MlsVinMiscDes16 { get; set; }
        public string MlsVinMiscDes17 { get; set; }
        public string MlsVinMiscDes18 { get; set; }
        public string MlsVinMiscDes19 { get; set; }
        public string MlsVinMiscDes20 { get; set; }
    }
}